name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build C# Code
      run: dotnet build
    
    - name: NPM Install 
      run: npm install 
      working-directory: DotnetTemplate.Web 


