name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build C# Code
      run: dotnet build
    
    - name: npm install & build 
      run: |
        npm install 
        npm run build
      working-directory: DotnetTemplate.Web 

    - name: testing
      run: dotnet test 

    - name: npm t & lint runs
      run: |
        npm t 
        npm run lint
      working-directory: DotnetTemplate.Web 



