name: Continous Integration
on: [push]

jobs:
    build:
        name: Build & Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Hello World 
              run: echo 'Hello World'
              uses: actions/hello-world-javascript-action@v1.1 # Name of the action. This uses https://github.com/actions/hello-world-javascript-action
               with:                                
            
                who-to-greet: 'Mona the Octocat'
